apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  user: {{ .Values.secrets.data.user | b64enc }}
  password: {{ .Values.secrets.data.password  | b64enc }}
  dbname: {{ .Values.secrets.data.dbname  | b64enc }}
  dbstring: {{ .Values.secrets.data.dbstring  | b64enc }}