app:
  replicas: 2
  env: qa
  container:
    image: baharul1987/pythonapp:latest
    containerport: 5000
  computerc:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 250Mi

hpa:
  enabled: false

ingress:
  service:
    name: flaskpp-svc
    port: 80

postgresql:
  enabled: true
  persistence:
    enabled: true
    size: 5Gi