apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
spec:
  storageClassName: manual
  resources:
    requests:
      storage: {{ .Values.persistentvolume.storage }}
  accessModes:
    - ReadWriteOnce
