apiVersion: v1
kind: Service
metadata:
  name: flaskapp-svc
  labels:
    {{- include "flaskapp.labels" . | nindent 4  }}
spec:
  selector:
    app: flaskapp
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000